spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: team_a
    password: green502
    url: jdbc:mariadb://localhost:3306/board

#mybatis:
#  type-aliases-package: com.example.boardpractice
#  mapper-locations: mapper/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

#file:
#  dir: /download/board3
