spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: green502
    url: jdbc:mariadb://localhost:3306/todo

mybatis:
  type-aliases-package: com.green.todotestapp
  mapper-locations: mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: /home/download

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mariadb://localhost:3306/todo_test
  sql:
    init:
      mode: always
      schema-locations: classpath:init/schema.sql
      data-locations: classpath:init/data.sql