spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: green502
    url: jdbc:mariadb://localhost:3306/todo

mybatis:
  type-aliases-package: com.green.todoapp.model
  mapper-locations: mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: /download/todo/

server:
  port: 8081