app:
  auth:
    header-scheme-name: authorization
    token-type: Bearer
    aceess-secret: DeaguGreenArtAcademyClass502ForJavaSpringBoot
    accessTokenExpiry: 200000
    refresh-secret: ForJavaSpringBootClass502DaeguGreenArtAcademy
    refreshTokenExpiry: 1296000000
    redis-access-black-key: "Z-AT-BLACK"
    redis-refresh-key: "Z-RT"
  oauth2:
    authorized-redirect-uris:
      - http://localhost:8082/oauth/redirect

mybatis:
  type-aliases-package: com.green.greengram
  mapper-locations: mappers/**/*.xml

spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greengram
    username: root
    password: green502
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 786396401983-6ihnqoufibjeome0eh80e76t2dn1t0vn.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1451077752307202
            client-secret: e0c4d98fec62419c46ec4fdaf57d0a1e
            scope:
              - email
              - public_profile
          naver:
            client-id: Lza8H5OX2xfNFHiRCw3W
            client-secret: ZPSVt_IUat
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          kakao:
            client-id: b6f58501970d4f912a1db0bbe8cc6fae
            client-secret: UqexmGleJuIuo3Fv3O04y8l9520TVp2i
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# cors
cors:
  allowed-origins: 'http://localhost:8082'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/home/download

server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    url: jdbc:mariadb://localhost:3306/greengram_test
file:
  dir: D:/home/download

---

spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 192.168.0.144
  datasource:
    url: jdbc:mariadb://192.168.0.144:3306/team_z
file:
  dir: /home/download
server:
  port: 8080