spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: team_a
    password: green502
    jdbc-url: jdbc:mariadb://192.168.0.144:3306/team_a

mybatis:
  type-aliases-package: com.example.boardpractice
  mapper-locations: mapper/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: /download/board3

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mariadb://localhost:3306/board_test
    username: root
  sql:
    init:
      mode: always
      schema-locations: init/schema.sql
      data-locations: init/data.sql