spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: green502
    url: jdbc:mariadb://localhost:3306/not_todo_test

mybatis:
  type-aliases-package: com.example.nottodolisttest
  mapper-locations: mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html
#    operations-sorter: alpha

server:
  port: 8081